# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-03 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_system', '0004_classes_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classestostudent',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_system.Classes'),
        ),
        migrations.AlterField(
            model_name='classestostudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classtoteacher',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_system.Classes'),
        ),
        migrations.AlterField(
            model_name='classtoteacher',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
